In [1]:
import os
import numpy

In [6]:
file_location = os.path.join('data', 'water.xyz')
water_coord = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
print(water_coord)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [7]:
atom_list = water_coord[:,0]
print(atom_list)

['O' 'H1' 'H2']


In [8]:
number_of_atoms = len(atom_list)
print(number_of_atoms)

3


In [10]:
coordinates = water_coord[:,1:]
coordinates = coordinates.astype(numpy.float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [20]:
for num1 in range(0,number_of_atoms):
    for num2 in range(0,number_of_atoms):
        x_dist = coordinates[num2,0] - coordinates[num1,0] 
        y_dist = coordinates[num2,1] - coordinates[num1,1]  
        z_dist = coordinates[num2,2] - coordinates[num1,2]
        bond_len = numpy.sqrt(x_dist**2 + y_dist**2 + z_dist**2)
        print(F'{atom_list[num1]} to {atom_list[num2]} is {bond_len}')

O to O is 0.0
O to H1 is 0.9690005374652793
O to H2 is 0.9690003348647513
H1 to O is 0.9690005374652793
H1 to H1 is 0.0
H1 to H2 is 1.52693633514957
H2 to O is 0.9690003348647513
H2 to H1 is 1.52693633514957
H2 to H2 is 0.0
